routes/web.php
<?php

use App\Http\Controllers\ClientesController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', [LoginController::class, 'loginForm'])->name('form.login');
Route::post('login', [LoginController::class, 'login'])->name('login');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->prefix('admin')->group(function () {
    // Dashboard route
    Route::get('/', [DashboardController::class, 'index'])->name('admin.index');

    // Clients routes
    Route::resource('clients', ClientesController::class, ['as' => 'admin'])->except('show');
});

app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientRequest;
use App\Models\Client;
use Illuminate\Http\Request;

class ClientesController extends Controller
{
    /**
     * @var App\Models\Client
     */
    private $client;

    public function __construct(Client $client)
    {
        $this->client = $client;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $clients = $this->client->orderBy('codigo', 'DESC')->paginate(10);

        return view('admin.clientes.index')->with([
            'clients' => $clients,
            'viewTitle' => trans("Clients")
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.clientes.create')->with([
            'model' => $this->client,
            'viewTitle' => trans("Create Client"),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientRequest $request)
    {   
        try {
            $this->client->create($request->all());
            return redirect()->route('admin.clients.index')->with('alert', [
                'type' => 'success',
                'message' =>trans("Client Created!"),
            ]);
        } catch(\Exception $e) {
            return redirect()->route('admin.clients.index')->with('alert', [
                'type' => 'danger',
                'message' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($hash)
    {
        try {
            $client = $this->client->whereHash($hash)->first();
            if(empty($client)) {
                return redirect()->route('admin.clients.index')->with('alert', [
                    'type' => 'danger',
                    'message' =>trans("Client not found"),
                ]);
            }
        
            return view('admin.clientes.edit')->with([
                'model' => $client,
                'viewTitle' => trans("Edit").": ".$client->nome
            ]);
        } catch(\Exception $e) {
            return redirect()->route('admin.index')->with('alert', [
                'type' => 'danger',
                'message' =>trans("Something happened, try again latter"),
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClientRequest $request, $hash)
    {
        try {
            $client = $this->client->whereHash($hash)->first();

            if(empty($client)) {
                return redirect()->route('admin.clients.index')->with('alert', [
                    'type' => 'danger',
                    'message' =>trans("Client not found"),
                ]);
            }

            $client->update($request->all());

            return redirect()->route('admin.clients.edit', $client->hash)->with('alert', [
                'type' => 'success',
                'message' =>trans("Client Updated!"),
            ]);
        } catch (\Exception $e) {
            return redirect()->route('admin.index')->with('alert', [
                'type' => 'danger',
                'message' =>trans("Something happened, try again latter"),
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($hash)
    {
        try {
            $client = $this->client->whereHash($hash)->first();

            if(empty($client)) {
                return redirect()->route('admin.clients.index')->with('alert', [
                    'type' => 'danger',
                    'message' =>trans("Client not found"),
                ]);
            }
    
            $client->delete();
    
            return redirect()->route('admin.clients.index')->with('alert', [
                'type' => 'success',
                'message' =>trans("Client Deleted!"),
            ]);
        } catch (\Exception $e) {
            return redirect()->route('admin.index')->with('alert', [
                'type' => 'danger',
                'message' =>trans("Something happened, try again latter"),
            ]);
        }
    }
}

resources/views/admin/clientes/create.blade.php
@extends('layouts.admin.master')

@section('content')
    @include('admin.clientes.form', ['action' => route('admin.clients.store'), 'edit' => false])
@endsection

@section('scripts')
@endsection

resources/views/admin/clientes/edit.blade.php
@extends('layouts.admin.master')

@section('content')
    @include('admin.clientes.form', ['action' => route('admin.clients.update', $model->hash), 'edit' => true])
@endsection

@section('scripts')
@endsection

resources/views/admin/clientes/form.blade.php
<div class="row">
    <div class="col-md-12">
        <form action="{{$action}}" method="POST">
            <div class="form-group d-flex justify-content-end">
                <a  class="btn btn-light-outline mr-2" href="{{route('admin.clients.index')}}">{{ trans('Go Back') }}</a>
                <button class="btn btn-primary" type="submit">{{trans('Save')}}</button>
            </div>
            <!-- /.form-group -->

            @csrf
            @if ($edit)
                @method('PUT')
            @endif
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="nome" class="label">{{trans('Complete Name')}}</label>
                        <input id="nome" type="text" name="nome" class="form-control" value="{{ old("nome", $model->nome) }}">
                        @error("nome")
                            <small class="text-danger form-text">{{$message}}</small>
                        @enderror
                    </div>
                    <!-- /.form-group -->
                </div>
                <!-- /.col-md-6 -->
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="data_nascimento">{{trans('Birthday Date')}}</label>
                        <input id="data_nascimento" name="data_nascimento" type="date" class="form-control" value="{{ old("data_nascimento", $model->data_nascimento->format('Y-m-d')) }}">
                        @error("data_nascimento")
                            <small class="text-danger form-text">{{$message}}</small>
                        @enderror
                    </div>
                    <!-- /.form-group --> 
                </div>
                <!-- /.col-md-3 -->
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="cpf">{{trans('CPF')}}</label>
                        <input id="cpf" name="cpf" type="text" class="form-control js-mask-cpf" value="{{ old("cpf", $model->cpf) }}">
                        @error("cpf")
                            <small class="text-danger form-text">{{$message}}</small>
                        @enderror
                    </div>
                    <!-- /.form-group --> 
                </div>
                <!-- /.col-md-3 -->
            </div>
            <!-- /.row -->
         
   

            <div class="form-group">
                <label for="telefone" class="label">{{trans('Phone')}}</label>
                <input id="telefone" type="text" name="telefone" class="form-control js-mask-phone" value="{{ old("telefone", $model->telefone) }}">
                @error("telefone")
                    <small class="text-danger form-text">{{$message}}</small>
                @enderror
            </div>
            <!-- /.form-group --> 

            <div class="form-group">
                <label for="email" class="label">{{trans('Email')}}</label>
                <input id="email" type="email" name="email" class="form-control js-mask-email" value="{{ old("email", $model->email) }}">
                @error("email")
                    <small class="text-danger form-text">{{$message}}</small>
                @enderror
            </div>
            <!-- /.form-group --> 
        

          
        </form>
    </div>
    <!-- /.col-md-12-->
</div>
<!-- /.row-->

resources/views/admin/clientes/index.blade.php
@extends('layouts.admin.master')

@section('content')
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary" href="{{route('admin.clients.create')}}">{{trans('Criar')}}</a>
    </div>

    <br>
    
    @if (! $clients->isEmpty())
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> {{trans('Code') }}</th>
                        <th> {{trans('Name') }}</th>
                        <th> {{trans('CPF') }}</th>
                        <th> {{trans('Phone') }}</th>
                        <th> {{trans('Email') }}</th>
                        <th> {{trans('Birthday Date') }}</th>
                        <th> #</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clients as $client)
                        <tr>
                            <td>{{$client->codigo}}</td>
                            <td>{{$client->nome}}</td>
                            <td>{{$client->cpf}}</td>
                            <td>{{$client->telefone}}</td>
                            <td>{{$client->email}}</td>
                            <td>{{$client->data_nascimento->format('d/m/Y')}}</td>
                            <td>
                                <div class="d-flex">
                                    <a class="btn btn-info btn-sm mr-3" href="{{ route('admin.clients.edit', $client->hash) }}"> {{trans('Edit')}}</a> 
    
                                    <form class="m0" method="POST" action="{{ route('admin.clients.destroy', $client->hash) }}">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-danger btn-sm" href=""> {{trans('Delete')}}</button> 
                                    </form>
                                </div>
                                <!-- /.d-flex -->
                            </td>
                        </tr>                    
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
        {{$clients->links()}}
    @else
        <h4>{{trans('No data found')}}</h4>
    @endif
@endsection

@section('scripts')
@endsection