routes/web.php
<?php

use App\Http\Controllers\ClientesController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', [LoginController::class, 'loginForm'])->name('form.login');
Route::post('login', [LoginController::class, 'login'])->name('login');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware(['auth'])->prefix('admin')->group(function () {
    // Dashboard route
    Route::get('/', [DashboardController::class, 'index'])->name('admin.index');

    // Clients routes
    Route::resource('clients', ClientesController::class, ['as' => 'admin'])->except('show');
});

resources/views/layouts/admin/components/admin-alerts.blade.php
@if (session('alert'))
<div class="row mb-3">
    <div class="col-md-12">
        <div class="alert alert-{{session('alert')['type'] ? session('alert')['type'] : 'warning'}} alert-dismissible fade show" role="alert">
            {{ session('alert')['message'] }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
             </button>
        </div>
        <!-- /.alert -->
    </div>
    <!-- /.col-md-12 -->
</div>
<!-- /.row -->
@endif

resources/views/layouts/admin/components/admin-head-assets.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Teste Adsomos">
<meta name="author" content="Lucas Guilherme">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="base-url" content="{{ URL::to('/') }}">

{{-- <link rel="icon" type="image/png" sizes="16x16" href="{{ mix('assets/img/favicon.png') }}"> --}}
<title>{{ config('app.name') }}</title>

@yield('styles')
<link href="{{ mix('assets/css/app.min.css') }}" rel="stylesheet">

resources/views/layouts/admin/components/admin-nav.blade.php
<nav style="border-bottom: 1px solid #f2f2f2;" class="navbar navbar-light sticky-top py-1 bg-white navbar-expand-lg ">
    <div class="container">
        <a class="navbar-brand" href="{{route('admin.index')}}">
          <img src="{{asset('assets/img/logo.png')}}" alt="Logo">
        </a>    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
              <a class="d-md-inline-block nav-link" href="{{route('admin.clients.index')}}">{{ trans('Clients') }}</a>
              </li>
              <li class="nav-item">
                <a class="d-md-inline-block btn btn-outline-dark" href="{{route('logout')}}">{{ trans('Logout') }}</a>
              </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/admin/components/admin-view-title.blade.php
@if (!empty($viewTitle))
<div class="row mb-3">
    <div class="col-md-12">
        <h3>{{$viewTitle}}</h3>
    </div>
    <!-- /.col-md-12 -->    
</div>
<!-- /.row -->
@endif